### ISSUE TITLE
Timeout example

### ISSUE THREAD

**Issue by wishinghand** [egoist/vue-router-prefetch#12]
Is the `timeout` option per route? I tried it with a 10 second timeout (10000ms) and it didn't seem to delay the loading of the route at all. I'd love to see a working example in the repo.

**Comment by egoist** [comment]
That's actually a bug, we should pass the `timeout` option to `setTimeout` here: https://github.com/egoist/vue-router-prefetch/blob/396a7fed480b451da15ebdc94dd529bcaf1d896f/src/index.js#L22
