### ISSUE TITLE
Cannot read property '_init' of undefined on a default vue CLI project with Typescript

### ISSUE THREAD

**Issue by gijsroge** [egoist/vue-router-prefetch#7]
Version: 1.5.1
Repo to reproduce: https://github.com/gijsroge/vue-router-prefetch-issue

This is a clean vue cli project with Typescript & Vue class component. 

It seems to have an issue with booting the plugin right when you start the app. (see error below)

![image](https://user-images.githubusercontent.com/2242498/55905065-80e08100-5bd1-11e9-9e89-287be4eeee07.png)

`vue.runtime.esm.js?2b0e:5148 Uncaught TypeError: Cannot read property '_init' of undefined
    at Catalogue (vue.runtime.esm.js?2b0e:5148)
    at VueComponent.linkPrefetch (index.mjs?4f85:1)
    at eval (index.mjs?4f85:1)
    at Array.forEach (<anonymous>)
    at IntersectionObserver.u (index.mjs?4f85:1)`

**Comment by Djaler** [comment]
Same thing. Looks like this plugin doesn't work with vue-class-component

**Comment by Djaler** [comment]
Thanks!
